<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VehicleHealthTracker.Application/VehicleHealthTracker.Application.csproj" />
    <ProjectReference Include="../VehicleHealthTracker.Infrastructure/VehicleHealthTracker.Infrastructure.csproj" />
  </ItemGroup>
</Project>
